package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.*;
import fatec.poo.model.Recepcionista;
import fatec.poo.model.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import java.time.format.DateTimeParseException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nicol
 */
public class RegistroHospedagem extends javax.swing.JFrame {

    /**
     * Creates new form RegistroHospede
     */
    public RegistroHospedagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSituacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtRegFunc = new javax.swing.JTextField();
        txtNumQuarto = new javax.swing.JTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtDataEntrada = new javax.swing.JFormattedTextField();
        ftxtDataSaida = new javax.swing.JFormattedTextField();
        btnSelRecepcionista = new javax.swing.JButton();
        btnSelHospede = new javax.swing.JButton();
        lblValorHospedagem = new javax.swing.JLabel();
        lblRecepcionista = new javax.swing.JLabel();
        lblHospede = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        btnLiberar = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSituacao.setText("...");
        btnSituacao.setEnabled(false);
        btnSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSituacaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Registro Funcional");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF Hóspede");

        jLabel4.setText("Nº. Quarto");

        jLabel5.setText("Data entrada");
        jLabel5.setToolTipText("");

        jLabel6.setText("Data saída");

        jLabel7.setText("Valor Hospedagem");

        jLabel8.setText("Situação");

        txtRegFunc.setEnabled(false);

        txtNumQuarto.setEnabled(false);

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPF.setText("");
        ftxtCPF.setEnabled(false);

        try {
            ftxtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataEntrada.setText("");
        ftxtDataEntrada.setEnabled(false);

        try {
            ftxtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataSaida.setText("");
        ftxtDataSaida.setEnabled(false);

        btnSelRecepcionista.setText("...");
        btnSelRecepcionista.setEnabled(false);
        btnSelRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelRecepcionistaActionPerformed(evt);
            }
        });

        btnSelHospede.setText("...");
        btnSelHospede.setEnabled(false);
        btnSelHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelHospedeActionPerformed(evt);
            }
        });

        lblValorHospedagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblRecepcionista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblSituacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftxtCPF)
                                    .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftxtDataEntrada)
                                    .addComponent(ftxtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValorHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtRegFunc)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelHospede)
                                .addGap(18, 18, 18)
                                .addComponent(lblHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(btnSituacao)
                                .addGap(18, 18, 18)
                                .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelRecepcionista)
                                .addGap(18, 18, 18)
                                .addComponent(lblRecepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftxtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorHospedagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        registro = null;

        try {
            registro = daoRegistro.consultar(Integer.parseInt(txtCodigo.getText()));

            if (registro == null) {
                txtRegFunc.setEnabled(true);
                btnConsultar.setEnabled(false);
                txtCodigo.setEnabled(false);
                btnReservar.setEnabled(true);

                txtRegFunc.requestFocus();
                btnSelRecepcionista.setEnabled(true);

            } else {

                if (registro.getDataSaida() != null) {
                    ftxtDataSaida.setText(registro.getDataSaida().format(dtf));
                    lblValorHospedagem.setText(String.valueOf(registro.getValorHospedagem()));
                } else {
                    btnLiberar.setEnabled(true);
                    ftxtDataSaida.setEnabled(true);
                    txtCodigo.setEnabled(false);
                    ftxtDataSaida.requestFocus();

                }

                txtRegFunc.setText(String.valueOf(registro.getRecepcionista().getRegFunc()));
                ftxtCPF.setText(registro.getHospede().getCpf());
                txtNumQuarto.setText(String.valueOf(registro.getQuarto().getNumero()));

                ftxtDataEntrada.setText(registro.getDataEntrada().format(dtf));
                lblRecepcionista.setText(registro.getRecepcionista().getNome());
                lblHospede.setText(registro.getHospede().getNome());
                lblRecepcionista.setText(registro.getRecepcionista().getNome());

                if (!registro.getQuarto().getSituacao()) {
                    lblSituacao.setText("Livre");
                } else {
                    lblSituacao.setText("Ocupado");
                }

                btnConsultar.setEnabled(false);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um codigo valido", "Dados inválidos", JOptionPane.WARNING_MESSAGE);
            txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD2213017", "BD2213017");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@ 192.168.1.6:1521:xe");
        daoRegistro = new DaoRegistro(conexao.conectar());
        daoRecepcionista = new DaoRecepcionista(conexao.conectar());
        daoQuarto = new DaoQuarto(conexao.conectar());
        daoHospede = new DaoHospede(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed

        try {
            registro.setDataSaida(LocalDate.parse(ftxtDataSaida.getText(), dtf));
            if (registro.getDataSaida().isBefore(registro.getDataEntrada())) {
                JOptionPane.showMessageDialog(null, "Digite uma data válida", "Data inválida", JOptionPane.WARNING_MESSAGE);
                ftxtDataSaida.requestFocus();
            } else {
                lblValorHospedagem.setText(String.valueOf(registro.liberarQuarto()));
                daoQuarto.alterar(registro.getQuarto());
                btnLiberar.setEnabled(false);
                ftxtDataSaida.setEnabled(false);
                if (registro.getQuarto().getSituacao() == false) {
                    lblSituacao.setText("Livre");
                } else {
                    lblSituacao.setText("Ocupado");
                }

                daoRegistro.alterar(registro);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite uma data válida", "Data inválida", JOptionPane.WARNING_MESSAGE);
            ftxtDataSaida.requestFocus();
        }
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed

        
        try {
            LocalDate data = LocalDate.parse(ftxtDataEntrada.getText(), dtf);
            registro = new Registro(Integer.parseInt(txtCodigo.getText()), data, recepcionista);
            registro.reservarQuarto(hospede, quarto);
            daoQuarto.alterar(registro.getQuarto());
            daoRegistro.inserir(registro);

            btnReservar.setEnabled(false);
            btnLiberar.setEnabled(false);
            ftxtDataEntrada.setEnabled(false);
            ftxtDataEntrada.setText("");
            btnConsultar.setEnabled(true);

            txtRegFunc.setText("");
            ftxtCPF.setText("");
            txtNumQuarto.setText("");
            txtCodigo.setText("");
            ftxtDataSaida.setText("");
            lblValorHospedagem.setText("");
            lblRecepcionista.setText("");
            lblHospede.setText("");
            lblSituacao.setText("");

            txtCodigo.setEnabled(true);
            txtCodigo.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data de Entrada inválida", "Data inválida", JOptionPane.WARNING_MESSAGE);
            ftxtDataEntrada.requestFocus();
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnSelRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelRecepcionistaActionPerformed
        recepcionista = null;

        try {
            recepcionista = daoRecepcionista.consultar(Integer.parseInt(txtRegFunc.getText()));
            lblRecepcionista.setText(recepcionista.getNome());

            txtRegFunc.setEnabled(false);
            btnSelRecepcionista.setEnabled(false);
            btnSelHospede.setEnabled(true);
            ftxtCPF.setEnabled(true);

            ftxtCPF.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Recepcionista não cadastrado", "", JOptionPane.WARNING_MESSAGE);
            txtRegFunc.requestFocus();
        }
    }//GEN-LAST:event_btnSelRecepcionistaActionPerformed

    private void btnSelHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelHospedeActionPerformed
        hospede = null;

        try {
            String cpf = ftxtCPF.getText().replace(".", "").replace("-", "");
            hospede = daoHospede.consultar(cpf);

            lblHospede.setText(hospede.getNome());

            ftxtCPF.setEnabled(false);
            btnSelHospede.setEnabled(false);

            txtNumQuarto.setEnabled(true);
            btnSituacao.setEnabled(true);

            txtNumQuarto.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hóspede não cadastrado", "", JOptionPane.WARNING_MESSAGE);
            ftxtDataSaida.requestFocus();
        }
    }//GEN-LAST:event_btnSelHospedeActionPerformed

    private void btnSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSituacaoActionPerformed
        quarto = null;
        try {
            quarto = daoQuarto.consultar(Integer.parseInt(txtNumQuarto.getText()));

            if (!quarto.getSituacao()) {
                lblSituacao.setText("Livre");
                ftxtDataEntrada.setEnabled(true);
                btnReservar.setEnabled(true);

                txtNumQuarto.setEnabled(false);
                btnSituacao.setEnabled(false);
                ftxtDataEntrada.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Quarto Ocupado", "", JOptionPane.INFORMATION_MESSAGE);
                txtNumQuarto.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Quarto não cadastrado", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSituacaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelHospede;
    private javax.swing.JButton btnSelRecepcionista;
    private javax.swing.JButton btnSituacao;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtDataEntrada;
    private javax.swing.JFormattedTextField ftxtDataSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHospede;
    private javax.swing.JLabel lblRecepcionista;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblValorHospedagem;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumQuarto;
    private javax.swing.JTextField txtRegFunc;
    // End of variables declaration//GEN-END:variables
    Registro registro = null;
    DaoRegistro daoRegistro = null;

    Recepcionista recepcionista = null;
    DaoRecepcionista daoRecepcionista = null;

    Hospede hospede = null;
    DaoHospede daoHospede = null;

    Quarto quarto = null;
    DaoQuarto daoQuarto = null;
    Conexao conexao = null;

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

}
